
<div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9"> 
         <form action="<?php echo $this->baseUrl('student/update');?>" method="post" class="form-horizontal" role="form">
         <div class="form-group">
       <label for="sname" class="col-sm-2 control-label">学号</label>
       <div class="col-sm-8">
           <input type="hidden" name="s_no" value="<?php echo $this->result[0]['s_no'];?>">
          <input type="sname" class="form-control input"  placeholder="" value="<?php echo $this->result[0]['s_no'];?>" disabled>
        </div>
       </div>
      
          <div class="form-group">
       <label for="sname" class="col-sm-2 control-label">姓名</label>
       <div class="col-sm-8">
          <input type="sname" class="form-control input" name="s_name" placeholder="" value="<?php echo $this->result[0]['s_name'];?>">
        </div>
       </div>
      
       <div class="form-group">
       <label for="sname" class="col-sm-2 control-label">性别</label>
       <div class="col-sm-8">
          <select class="form-control" name="s_sex">
            <?php if($this->result[0]['s_sex'] == '男'):?>
              <option   selected>男</option>
              <option  >女</option>
            <?php else:?>
              <option   >男</option>
              <option  selected>女</option>
            <?php endif;?>
          </select>
        </div>
       </div>
      
       <div class="form-group">
       <label for="sname" class="col-sm-2 control-label">电话</label>
       <div class="col-sm-8">
          <input type="sname" class="form-control" name="s_phone" placeholder="" value="<?php echo $this->result[0]['s_phone'];?>">
        </div>
       </div>
      
       <div class="form-group">
       <label for="sname" class="col-sm-2 control-label">学院</label>
       <div class="col-sm-8">
          <input type="sname" class="form-control" name="department" placeholder="" value="<?php echo $this->result[0]['department'];?>">
        </div>
       </div>
      
       <div class="form-group">
       <label for="sname" class="col-sm-2 control-label">专业</label>
       <div class="col-sm-8">
          <input type="sname" class="form-control" name="major" placeholder="" value="<?php echo $this->result[0]['major'];?>">
        </div>
       </div>
      
       <div class="form-group">
       <label for="sname" class="col-sm-2 control-label">班级</label>
       <div class="col-sm-8">
          <input type="sname" class="form-control" name="class" placeholder="" value="<?php echo $this->result[0]['class'];?>">
        </div>
       </div>
      

       <div class="form-group">
       <label for="sname" class="col-sm-2 control-label">入住日期</label>
       <div class="col-sm-8">
          <input type="sname" class="form-control" name="live_time" placeholder="" value="<?php echo $this->result[0]['live_time'];?>">
        </div>
       </div>
      
         <div class="form-group">
       <label for="sname" class="col-sm-2 control-label">楼号</label>
       <div class="col-sm-8">
         <select name="b_no" class="form-control">
           <?php foreach($this->building as $key => $value):?>
             <?php if($key == 0):?>
              <option  selected><?php echo $value['b_no'];?></option>
              <?php else:?>
              <option ><?php echo $value['b_no'];?></option>
              <?php endif;?>
            <?php endforeach;?>
          </select>
          <!-- <input type="sname" class="form-control" name="b_no" placeholder="" value="<?php echo $this->result[0]['b_no'];?>"> -->
        </div>
       </div>
       <div class="form-group">
       <label for="sname" class="col-sm-2 control-label">宿舍号</label>
       <div class="col-sm-8">
         <select name="d_no" class="form-control">
           <option  <?php if($this->result[0]['d_no']=='601') echo 'selected';?>>601</option>
           <option  <?php if($this->result[0]['d_no']=='602') echo 'selected';?>>602</option>
           <option  <?php if($this->result[0]['d_no']=='603') echo 'selected';?>>603</option>
           <option  <?php if($this->result[0]['d_no']=='604') echo 'selected';?>>604</option>
           <option  <?php if($this->result[0]['d_no']=='605') echo 'selected';?>>605</option>
         </select>
          <!-- <input type="sname" class="form-control" name="d_no" placeholder="" value="<?php echo $this->result[0]['d_no'];?>"> -->
        </div>
       </div>
       <div class="form-group">
       <label for="sname" class="col-sm-2 control-label"></label>
       <div class="col-sm-8">
          <button onclick="history.back()" type="button" class="btn btn-default" data-dismiss="modal">取消</button>
          <button type="submit" class="btn btn-primary">保存</button>
        </div>
       </div>
       
            </form>
        </div>

        <div class="col-xs-6 col-sm-3 sidebar-default" id="sidebar" role="navigation">
              <div class="list-group">
                <a href="<?php echo $this->baseUrl('home');?>" class="list-group-item ">主页</a>
                <a href="<?php echo $this->baseUrl('student');?>" class="list-group-item active">学生信息管理</a>
                <a href="<?php echo $this->baseUrl('dormitory');?>" class="list-group-item">宿舍管理</a>
                <a href="<?php echo $this->baseUrl('worker');?>" class="list-group-item">宿舍工作人员管理</a>
                <a href="<?php echo $this->baseUrl('visitor');?>" class="list-group-item">来访人员管理</a>
              </div>
          </div>
</div>
