<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>宿舍管理系统-登录</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $this->baseUrl();?>/css/bootstrap_metro.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?php echo $this->baseUrl();?>/css/login.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="<?php echo $this->baseUrl();?>/js/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?php echo $this->baseUrl();?>/js/bootstrap.min.js"></script>
  </head>

  <body>

    <div class="container">

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">提示</h4>
              </div>
              <div class="modal-body">
                用户名或密码错误！请重试！
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        <?php if($this->error):?>
        <script type="text/JavaScript">$('#myModal').modal('show');</script>
      <form class="form-signin" role="form" action="<?php echo $this->baseUrl().'/login/check';?>" method="post">
        <h2 class="form-signin-heading">欢迎使用宿舍管理系统，请登录</h2>
        <input type="text" class="form-control" placeholder="Email address" required autofocus name="uid">
        <input type="password" class="form-control" placeholder="Password" required name="pwd">
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> 记住我
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
      </form>
      <?php else:?>
      <form class="form-signin" role="form" action="<?php echo $this->baseUrl().'/login/check';?>" method="post">
        <h2 class="form-signin-heading">欢迎使用宿舍管理系统，请登录</h2>
        <input type="text" class="form-control" placeholder="Email address" required autofocus name="uid">
        <input type="password" class="form-control" placeholder="Password" required name="pwd">
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> 记住我
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
      </form>
  <?php endif;?>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>
