<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>学生宿舍管理系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Loading Bootstrap -->
    <link href="<?php echo $this->baseUrl();?>/css/bootstrap_metro.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="<?php echo $this->baseUrl();?>/css/offcanvas.css" rel="stylesheet">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-fixed-top navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="<?php echo $this->baseUrl('home');?>">学生宿舍管理系统</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo $this->baseUrl('home');?>">主页</a></li>
            <li><a href="<?php echo $this->baseUrl('about');?>">关于</a></li>
            <li><a href="<?php echo $this->baseUrl('contact');?>">联系我</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">欢迎您，
            <?php $session = new Zend_Session_Namespace();
            $name = $session->login['name'];
            if($name) echo $name; else echo '' ;?></a></li>
            <li><a href="<?php echo $this->baseUrl('login/logout');?>">退出</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
<!--       <div class="navbar-header" >navbar-header</div> -->
    </div><!-- /.navbar -->
    <div class="container">


        <?php echo $this->layout()->content; ?>

      <hr>

      <footer>
        <p>&copy; 张智励 2014</p>
      </footer>

    </div><!--/.container-->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="<?php echo $this->baseUrl();?>/js/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?php echo $this->baseUrl();?>/js/bootstrap.min.js"></script>
    <script type="text/javascript">
    $("#delete,a[type=button]").click(function(){
        $("#del_ok").attr("href",$(this).attr('data'));
     });
    </script>
    <script type="text/javascript">
      $(document).ready(function() {
        $('[data-toggle=offcanvas]').click(function() {
          $('.row-offcanvas').toggleClass('active');
        });
      });
    </script>
  </body>
</html>