

      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">

          <div class="row">
            <div class="col-xs-6 col-sm-6 col-lg-6">
               <div class="well">
                <h2><span class="glyphicon glyphicon-user"></span><span style="margin-left: 10px;">学生信息</span></h2>
                 <p>总共：<?php echo $this->info['stu_num'];?>人</p>
              <p><a class="btn btn-default" href="<?php echo $this->baseUrl('student');?>" role="button">详情 &raquo;</a></p>
              </div>
            </div><!--/span-->
            <div class="col-xs-6 col-sm-6 col-lg-6">
              <div class="well">
              <h2><span class="glyphicon glyphicon-home"></span><span style="margin-left: 10px;">宿舍区信息</span></h2>
              <p>总共：<?php echo $this->info['building_num'].'栋，'.$this->info['dor_num'];?>间宿舍</p>
              <p><a class="btn btn-default" href="<?php echo $this->baseUrl('dormitory');?>" role="button">详情 &raquo;</a></p>
              </div>
            </div><!--/span-->
            <div class="col-xs-6 col-sm-6 col-lg-6">
              <div class="well">
              <h2><span class="glyphicon glyphicon-user"><span style="margin-left: 10px;">宿舍工作人员信息</span></h2>
              <p>总共：<?php echo $this->info['worker_num'];?>人 </p>
              <p><a class="btn btn-default" href="<?php echo $this->baseUrl('worker');?>" role="button">详情 &raquo;</a></p>
              </div>
            </div><!--/span-->
            <div class="col-xs-6 col-sm-6 col-lg-6">
              <div class="well">
              <h2><span class="glyphicon glyphicon-edit"></span><span style="margin-left: 10px;">来访人员信息</span></h2>
              <p>总共：<?php echo $this->info['v_num'];?>条记录 </p>
              <p><a class="btn btn-default" href="<?php echo $this->baseUrl('visitor');?>" role="button">详情 &raquo;</a></p>
              </div>
            </div><!--/span-->
          </div><!--/row-->
        </div><!--/span-->

        <div class="col-xs-6 col-sm-3 sidebar-default" id="sidebar" role="navigation">
          <div class="list-group">
            <a href="<?php echo $this->baseUrl('home');?>" class="list-group-item active">主页</a>
            <a href="<?php echo $this->baseUrl('student');?>" class="list-group-item">学生信息管理</a>
            <a href="<?php echo $this->baseUrl('dormitory');?>" class="list-group-item">宿舍管理</a>
            <a href="<?php echo $this->baseUrl('worker');?>" class="list-group-item">宿舍工作人员管理</a>
            <a href="<?php echo $this->baseUrl('visitor');?>" class="list-group-item">来访人员管理</a>
          </div>
        </div><!--/span-->
      </div><!--/row-->

